spring:
  datasource:
    url: ${db.pdn.log.server}?autoReconnect=true&useSSL=false
    username: ${db.pdn.general.user}
    password: ${db.pdn.general.password}

  boot:
    admin:
      client:
        url: ${spring.admin.clienturl}


  application:
    name: Middle Tier Log

  h2:
    console:
      enabled: false

logging.file: /var/log/jbr/MiddleTier-LogDB-PDN.log
logging:
  file:
    max-history: 3
    max-size: 100MB

server:
  port: 12001

log:
  service-name: middletier-logdb

info:
  app:
    version: Production
