spring:
  datasource:
    url: ${db.dev.log.server}?autoReconnect=true&useSSL=false
    username: ${db.dev.general.user}
    password: ${db.dev.general.password}

  boot:
    admin:
      client:
        url: ${spring.admin.clienturl}

  application:
    name: Middle Tier Log (Development)

  h2:
    console:
      enabled: false

logging.file: /var/log/jbr/MiddleTier-LogDB-DEV.log
logging:
  file:
    max-history: 3
    max-size: 100MB

server:
  port: 10001

log:
  service-name: middletier-logdb-dev

info:
  app:
    version: Development
